### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EzequielVilla** [stradalucas/apx-desafio-m6#1]
Buenas! Estoy intentando ingresar y me tira un error, esta intentando ir al backend con localhost:

![image](https://user-images.githubusercontent.com/81453859/149677288-ed22bd0f-5652-4609-9f8d-18f1570fa968.png)

Fijate si tenes bien cofigurada la variable de ambiente en heroku!

**Comment by FacundoEG** [comment]
@stradalucas Buenas! estoy igual que Eze, quiero entrar a la pagina y recibo el mismo error.

Si podes chequeate eso asi podemos darte el feedback!

**Comment by stradalucas** [comment]
¡Buenas! ¡Me faltaba configurar la variable de ambiente en Heroku!
